version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: |
          TAG=latest
          docker build -t vietnguyen148/chat-app:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push vietnguyen148/chat-app:$TAG


